### ISSUE TITLE
Uncaught TypeError: Can't read 'src' of 'null' @ about:blank:62:21

### ISSUE THREAD

**Issue by ZdrytchX** [fuzzykiller/batoto-grabber#1]
screenshot of error:
https://cdn.discordapp.com/attachments/249544867175333898/402782756519542786/unknown.png

**Comment by btzdnl** [comment]
Thanks for reporting this issue! You wouldn't happen to remember the series
that was visible when the error occurred?
ZdrytchX de Frisquilious ViruS <notifications@github.com> schrieb am Di.
16. Jan. 2018 um 12:17:

**Comment by soli18** [comment]
Got the same problem when starting the client bro

**Comment by ZdrytchX** [comment]
> Thanks for reporting this issue! You wouldn't happen to remember the series
that was visible when the error occurred?

Progress Bar: [1/565]
Page loaded: Forums: Comic (showing subcategories of comics section)

**Comment by btzdnl** [comment]
Wow, that doesn't sound right at all. It's definitely not supposed to go
there. Could you perhaps give me a copy of your "My Follows" page (HTML
only)? Do you have any sort of special access (contributor, mod, ...) to
Batoto? What's the first entry in your "My Follows" list?
ZdrytchX de Frisquilious ViruS <notifications@github.com> schrieb am Di.
16. Jan. 2018 um 16:39:

**Comment by ZdrytchX** [comment]
If you're on discord I can send you my follows html file.
No special access rights (mods/contributor etc.)
My first entry on My Follows (http://bato.to/myfollows) is "A "Dimwitted" Monk fell from Heaven"

edit: I tried removing the series form the list (since it seems to have whitespaces before the name) but your application still spits out the same error after removing it. It also visited the same comics forum page too without visiting any comic specifically

I'm currently on the batoto discord server too under the same username https://discord.gg/5N5Snhp

**Comment by btzdnl** [comment]
I'm not, sorry. If you're okay with making it public, you could use the
GitHub Gist feature. There should be no private information in the HTML,
except your username and the series you chose to follow of course.

Otherwise, you could use Dropbox or whatever and send me a link on Batoto.
ZdrytchX de Frisquilious ViruS <notifications@github.com> schrieb am Di.
16. Jan. 2018 um 17:03:

**Comment by ZdrytchX** [comment]
sent

**Comment by btzdnl** [comment]
Alright, figured it out. Your “My Follows” list contains yet another type of deleted series. It’s not visible “to the naked eye” because the title is also gone. However, a link to http://bato.to/comic/_/comics/-r remains. They’re always first on the list. At least it fails right away. 😅 

I’ll soon release a new version that ignores these invalid entries.

**Comment by ZdrytchX** [comment]
Alright cheers. Good luck debugging

**Comment by btzdnl** [comment]
Version 1.4 containing this fix is now available.
